using System.Diagnostics;
using System.Formats.Tar;
using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using ControlApi.Models;
using Docker.DotNet;
using Docker.DotNet.Models;

namespace ControlApi.Services;

// Every lookup filters on both the compose service label AND the compose project label, so this
// can never reach a container outside the sandbox stack it's meant to control - even if a caller
// passes an unexpected serviceId, Docker's own label filter (exact match) just returns nothing.
public class DockerService : IDockerService
{
    // gaiadocker/iproute2 is Pumba's own default tc-image (has the `tc` binary Pumba needs inside
    // the target's network namespace) - pinned explicitly rather than relying on Pumba's default
    // so the image we pre-pull always matches the one Pumba will actually ask Docker to run.
    private const string PumbaImage = "gaiaadm/pumba:latest";
    private const string TcImage = "gaiadocker/iproute2:latest";
    private const string ChaosTargetLabel = "control-api.chaos-target";
    private const string K6Image = "grafana/k6:latest";

    // link-api/redirect-api scale because nginx fronts them (see sandbox/infra/nginx/nginx.conf);
    // shortener-service/traffic-service scale as RabbitMQ competing consumers instead - no load
    // balancer involved, RabbitMQ itself round-robins unacked deliveries across every consumer on a
    // queue. Still an explicit allowlist, not "anything in the compose file", so a stateful/singleton
    // service (postgres, rabbitmq, pgcat, ...) isn't even an option to try by mistake - both workers
    // are volume-free, same property ScaleAsync already relies on for --force-recreate safety
    // elsewhere (see RunComposeAsync's own comment).
    private static readonly IReadOnlyList<string> ScalableServices = ["link-api", "redirect-api", "shortener-service", "traffic-service"];

    // Every DB-touching service - pgcat's toggle recreates all of them, since "the system without
    // connection pooling" means the whole system, not just the two APIs a k6 test happens to hit.
    private static readonly IReadOnlyList<string> DbTouchingServices =
        ["auth-api", "link-api", "redirect-api", "shortener-service", "traffic-service"];

    // Only these two actually read/populate the Redis cache (see LinkCacheService) - shortener-
    // service/traffic-service/auth-api have no cache to disable.
    private static readonly IReadOnlyList<string> CacheUsingServices = ["link-api", "redirect-api"];

    // The two standbys recovery_min_apply_delay can be set on - not the primary, which has no
    // concept of replay delay.
    private static readonly IReadOnlyList<string> PostgresReplicas = ["postgres-replica1", "postgres-replica2"];

    // SENTINEL SET is local to whichever Sentinel instance receives it - not gossiped to the other
    // two - so every config change loops over all three to keep them in sync.
    private static readonly IReadOnlyList<string> SentinelContainers = ["redis-sentinel-1", "redis-sentinel-2", "redis-sentinel-3"];

    // The three Redis data-plane containers whose actual replication role (see GetRedisTopologyAsync)
    // can change on its own via Sentinel failover, independent of anything this app does.
    private static readonly IReadOnlyList<string> RedisDataNodes = ["redis-master", "redis-replica1", "redis-replica2"];

    // The three-node Mongo replica set whose primary (see GetMongoTopologyAsync) is elected among
    // themselves, same "can change with no app involvement" story as Redis Sentinel above.
    private static readonly IReadOnlyList<string> MongoNodes = ["mongo1", "mongo2", "mongo3"];

    // The two RabbitMQ consumers - workers that each run a LinkCreatedConsumer and/or
    // ClickTrackedConsumer, all sharing RabbitMqConsumer's own _prefetchCount field.
    private static readonly IReadOnlyList<string> RabbitMqConsumingServices = ["shortener-service", "traffic-service"];

    // The real routes a traffic run's step sequence can be built from - the server-side source of
    // truth (see EndpointDefinition) so k6-scripts/flow.js stays a generic interpreter with no
    // built-in knowledge of this app's actual routes, and Program.cs can validate a request before
    // ever starting a k6 container. email/password/originalLink are auto-generated by flow.js once
    // per iteration (not per step) specifically so a Register followed by a Login in the same
    // sequence shares one identity instead of two, which is what makes that pairing meaningful to
    // chain at all - see flow.js for where those get seeded.
    private static readonly IReadOnlyList<EndpointDefinition> EndpointRegistry =
    [
        new(
            "auth-api.register", "auth-api", "POST", "/register",
            """{"name":"flow-user","email":"{{email}}","password":"{{password}}"}""",
            new Dictionary<string, string>(), [],
            "Register a new user with this iteration's generated email/password"),
        new(
            "auth-api.login", "auth-api", "POST", "/login",
            """{"email":"{{email}}","password":"{{password}}"}""",
            new Dictionary<string, string> { ["token"] = "token" }, ["email", "password"],
            "Log in - only succeeds if a Register step ran earlier in the same sequence (they share one generated email/password per iteration); alone, every attempt is an expected 401"),
        new(
            "link-api.create", "link-api", "POST", "/Links",
            """{"originalLink":"{{originalLink}}"}""",
            new Dictionary<string, string> { ["hash"] = "shortenLink" }, [],
            "Create a short link"),
        new(
            "redirect-api.resolve", "redirect-api", "GET", "/{{hash}}",
            null,
            new Dictionary<string, string>(), ["hash"],
            "Resolve a short link and redirect - uses the hash a Create step earlier in the sequence produced, a preloaded data pool if one was requested (see DataSourceRegistry), or a fixture link if neither ran. Right after Create in the same step, this often 404s: LinkApi returns the hash before ShortenerService has actually persisted it via RabbitMQ - a real eventual-consistency window, not a bug"),
    ];

    // What a run's optional DataPoolRequest can preload - see DataSourceDefinition for why this is
    // separate from EndpointRegistry above (a bulk paginated read done once before the run starts,
    // not a per-iteration call). ProducesVar "hash" is flow.js's own variable name, the same one
    // link-api.create's Produces entry writes to, so a preloaded pool and a live Create step both
    // feed the exact same downstream steps without flow.js needing to treat them differently.
    private static readonly IReadOnlyList<DataSourceDefinition> DataSourceRegistry =
    [
        new(
            "link-api.links", "link-api", "hash",
            "Existing short links, paged from GET /Links - use this to make a Resolve-only sequence hit varied real records instead of the same one fixture link every iteration"),
    ];

    // Reused across every FetchDataPoolAsync call rather than one-per-call - this instance is
    // itself a singleton service, so that's exactly the lifetime HttpClient is meant to be used at
    // (a fresh instance per call risks socket exhaustion under load, which is ironic for a load
    // testing tool to hit).
    private readonly HttpClient _httpClient = new();
    private readonly DockerClient _client;
    private readonly string _composeProject;
    private readonly string _composeNetwork;
    private readonly string _composeFile;
    private readonly string _k6ScriptsDir;
    private readonly string _pgcatConfigDir;
    private readonly ILogger<DockerService> _logger;

    // In-memory standing toggle state - see InfraStatus for why this is fine for a local sandbox
    // tool despite not surviving a control-api restart.
    private bool _nginxBypassed;
    private bool _pgcatEnabled = true;
    private bool _cacheEnabled = true;

    // Mirrors pgcat.toml's shipped defaults, collapsed to one shared value across all 3 pools
    // (the file itself differentiates links_db at 20 vs 10 for the other two - see
    // SetPgcatPoolSettingsAsync's own comment for why that's fine to lose once this control is used).
    private PgcatPoolSettings _pgcatPoolSettings = new("transaction", true, 10);

    // Mirrors RabbitMqConsumer's own hardcoded-turned-configurable default.
    private int _rabbitMqPrefetch = 10;

    // Mirrors the shipped default in docker-compose.yml's ConnectionStrings__Mongo.
    private string _mongoReadPreference = "primary";

    // Mirrors Npgsql's own default (and the shipped ${NPGSQL_MAX_POOL_SIZE:-100} fallback).
    private int _npgsqlPoolSize = 100;

    public DockerService(IConfiguration configuration, ILogger<DockerService> logger)
    {
        _logger = logger;
        _composeProject = configuration["Docker:ComposeProject"] ?? "sandbox";
        _composeNetwork = configuration["Docker:ComposeNetwork"] ?? $"{_composeProject}_default";
        _composeFile = configuration["Docker:ComposeFile"] ?? "/workspace/docker-compose.yml";
        _k6ScriptsDir = configuration["K6:ScriptsDir"] ?? Path.Combine(AppContext.BaseDirectory, "k6-scripts");
        _pgcatConfigDir = configuration["Pgcat:ConfigDir"] ?? "/pgcat-config";

        var endpoint = configuration["Docker:Endpoint"]
            ?? (OperatingSystem.IsWindows() ? "npipe://./pipe/docker_engine" : "unix:///var/run/docker.sock");
        _client = new DockerClientConfiguration(new Uri(endpoint)).CreateClient();
    }

    public async Task<IReadOnlyList<ManagedContainer>> ListContainersAsync(CancellationToken ct)
    {
        var containers = await _client.Containers.ListContainersAsync(new ContainersListParameters
        {
            All = true,
            Filters = new Dictionary<string, IDictionary<string, bool>>
            {
                ["label"] = new Dictionary<string, bool> { [$"com.docker.compose.project={_composeProject}"] = true },
            },
        }, ct);

        return containers
            .Select(ToStatus)
            .Where(status => status is not null)
            .Select(status => status!)
            .ToList();
    }

    public async Task<ManagedContainer?> StopAsync(string serviceId, CancellationToken ct)
    {
        var container = await FindAsync(serviceId, ct);
        if (container is null)
        {
            return null;
        }

        _logger.LogWarning("Stopping container {ServiceId} ({ContainerId})", serviceId, container.ID);
        await _client.Containers.StopContainerAsync(container.ID, new ContainerStopParameters { WaitBeforeKillSeconds = 10 }, ct);
        return await FindAsync(serviceId, ct) is { } updated ? ToStatus(updated) : null;
    }

    public async Task<ManagedContainer?> StartAsync(string serviceId, CancellationToken ct)
    {
        var container = await FindAsync(serviceId, ct);
        if (container is null)
        {
            return null;
        }

        _logger.LogWarning("Starting container {ServiceId} ({ContainerId})", serviceId, container.ID);
        await _client.Containers.StartContainerAsync(container.ID, new ContainerStartParameters(), ct);
        return await FindAsync(serviceId, ct) is { } updated ? ToStatus(updated) : null;
    }

    public async Task<ManagedContainer?> RestartAsync(string serviceId, CancellationToken ct)
    {
        var container = await FindAsync(serviceId, ct);
        if (container is null)
        {
            return null;
        }

        _logger.LogWarning("Restarting container {ServiceId} ({ContainerId})", serviceId, container.ID);
        await _client.Containers.RestartContainerAsync(container.ID, new ContainerRestartParameters { WaitBeforeKillSeconds = 10 }, ct);
        return await FindAsync(serviceId, ct) is { } updated ? ToStatus(updated) : null;
    }

    public async Task<ChaosAction?> DegradeAsync(string serviceId, ChaosRequest request, CancellationToken ct)
    {
        var target = await FindAsync(serviceId, ct);
        if (target is null)
        {
            return null;
        }

        await EnsureImageAsync(PumbaImage, ct);
        await EnsureImageAsync(TcImage, ct);

        var netemArgs = request.Type switch
        {
            ChaosType.Delay => new[] { "delay", "--time", request.Amount.ToString() },
            ChaosType.Loss => new[] { "loss", "--percent", request.Amount.ToString() },
            ChaosType.Partition => new[] { "loss", "--percent", "100" },
            _ => throw new ArgumentOutOfRangeException(nameof(request)),
        };

        var cmd = new List<string> { "netem", "--tc-image", TcImage, "--duration", $"{request.DurationSeconds}s" };
        cmd.AddRange(netemArgs);
        cmd.Add(target.ID);

        var created = await _client.Containers.CreateContainerAsync(new CreateContainerParameters
        {
            Image = PumbaImage,
            Cmd = cmd,
            Labels = new Dictionary<string, string>
            {
                ["com.docker.compose.project"] = _composeProject,
                [ChaosTargetLabel] = serviceId,
            },
            HostConfig = new HostConfig
            {
                Binds = ["/var/run/docker.sock:/var/run/docker.sock"],
                AutoRemove = true,
            },
        }, ct);

        _logger.LogWarning(
            "Starting {ChaosType} chaos against {ServiceId} for {Duration}s (pumba container {PumbaId})",
            request.Type, serviceId, request.DurationSeconds, created.ID);
        await _client.Containers.StartContainerAsync(created.ID, new ContainerStartParameters(), ct);

        return new ChaosAction(serviceId, created.ID, request.Type, request.DurationSeconds, DateTimeOffset.UtcNow);
    }

    public async Task<int> HealAsync(string serviceId, CancellationToken ct)
    {
        var chaosContainers = await _client.Containers.ListContainersAsync(new ContainersListParameters
        {
            All = true,
            Filters = new Dictionary<string, IDictionary<string, bool>>
            {
                ["label"] = new Dictionary<string, bool> { [$"{ChaosTargetLabel}={serviceId}"] = true },
            },
        }, ct);

        foreach (var chaos in chaosContainers)
        {
            _logger.LogWarning("Healing {ServiceId} early - stopping chaos container {ChaosId}", serviceId, chaos.ID);
            // Pumba's netem handler traps SIGTERM to tear down the tc rule before exiting, so a
            // plain stop (not a kill) is what lets the target's network actually recover.
            await _client.Containers.StopContainerAsync(chaos.ID, new ContainerStopParameters { WaitBeforeKillSeconds = 10 }, ct);
        }

        return chaosContainers.Count;
    }

    // k6 picks the elapsed-time format by the *total configured test duration*, not the current
    // elapsed value: under a minute it's plain "12.3s" for the whole run, but a run configured for
    // 60s or more prints "0m01.0s", "1m05.0s", etc. from the very first line onward - confirmed
    // against real runs at 10s vs 65s (identical scripts, only --duration differed). Groups:
    // 1=hours (optional), 2=minutes (optional), 3=seconds, 4=active VUs, 5=max VUs, 6=iterations.
    private static readonly Regex K6ProgressLine =
        new(@"running \((?:(\d+)h)?(?:(\d+)m)?(\d+(?:\.\d+)?)s\), (\d+)/(\d+) VUs, (\d+) complete", RegexOptions.Compiled);

    // flow.js reads STEPS_JSON's fields as plain camelCase JS property names (step.serviceId,
    // step.pathTemplate, ...) - .NET's default serializer would emit PascalCase from the record's
    // own property names otherwise.
    private static readonly JsonSerializerOptions StepJsonOptions = new(JsonSerializerDefaults.Web);

    private sealed record ResolvedStep(
        string Id, string ServiceId, string Method, string PathTemplate, string? BodyTemplate,
        IReadOnlyDictionary<string, string> Produces, double PauseAfterSeconds);

    public async Task<TrafficReport?> RunTrafficAsync(TrafficRequest request, Func<TrafficProgress, Task> onProgress, CancellationToken ct)
    {
        // Every run resolves its ordered step list against the server-side registry and executes
        // that exact sequence, once per k6 iteration, each step's own pause included - see flow.js.
        // Unknown ids are already rejected by Program.cs before this is ever called; the null
        // return here is just defense in depth.
        var resolvedSteps = new List<ResolvedStep>();
        foreach (var step in request.Steps)
        {
            var definition = EndpointRegistry.FirstOrDefault(e => e.Id == step.EndpointId);
            if (definition is null)
            {
                return null;
            }

            resolvedSteps.Add(new ResolvedStep(definition.Id, definition.ServiceId, definition.Method, definition.PathTemplate, definition.BodyTemplate, definition.Produces, step.PauseAfterSeconds));
        }

        if (resolvedSteps.Count == 0)
        {
            return null;
        }

        var scriptPath = Path.Combine(_k6ScriptsDir, "flow.js");
        if (!File.Exists(scriptPath))
        {
            return null;
        }

        await EnsureImageAsync(K6Image, ct);

        // A requested data pool is fetched from the real app now, before k6 even starts, and
        // reported through the same onProgress callback as the run itself (Phase "preparing") so
        // the UI can show it instead of a frozen "starting..." while a few hundred requests happen
        // server-side. Null SourceId (unknown - already rejected by Program.cs) falls back to no
        // pool rather than failing the whole run over it.
        string? poolVar = null;
        IReadOnlyList<string>? pool = null;
        if (request.DataPool is { Count: > 0 } poolRequest)
        {
            var source = DataSourceRegistry.FirstOrDefault(s => s.Id == poolRequest.SourceId);
            if (source is not null)
            {
                pool = await FetchDataPoolAsync(source, poolRequest.Count, onProgress, ct);
                poolVar = source.ProducesVar;
            }
        }

        // Exactly one of three shapes drives how the run ends - k6's own executors, not reimplemented:
        // a target iteration count (shared-iterations - flat VUs, runs until that many iterations are
        // done, however long that takes), a custom ramp (--stage per segment of the UI's point graph -
        // ramping-vus), or a flat --vus/--duration constant. k6's periodic "running (...), X/Y VUs, N
        // complete" status line keeps the same overall shape in all three (confirmed against real runs
        // of each before relying on it) - only the elapsed-time formatting depends on total duration
        // (K6ProgressLine above), and only iterations mode has no fixed total duration at all.
        var cmd = new List<string> { "run", "--no-color", "--summary-export", "/scripts/summary.json", "--vus", request.Vus.ToString() };
        int totalSeconds;
        int? targetIterations = request.Iterations;
        if (targetIterations is { } iterations)
        {
            cmd.Add("--iterations");
            cmd.Add(iterations.ToString());
            totalSeconds = 0;
        }
        else if (request.Stages is { Count: > 0 } stages)
        {
            foreach (var stage in stages)
            {
                cmd.Add("--stage");
                cmd.Add($"{stage.DurationSeconds}s:{stage.TargetVus}");
            }

            totalSeconds = stages.Sum(s => s.DurationSeconds);
        }
        else
        {
            cmd.Add("--duration");
            cmd.Add($"{request.DurationSeconds}s");
            totalSeconds = request.DurationSeconds;
        }

        cmd.Add("/scripts/scenario.js");

        // Nginx bypass only changes where k6 itself sends requests (LINK_API_URL/REDIRECT_API_URL
        // env vars the scripts already read - see smoke.js) - nginx keeps running either way, so
        // the frontend app's own manual use of it is unaffected. Bypassing means requests go
        // straight to the compose service name, which Docker's embedded DNS still round-robins
        // across replicas per-connection, but k6 keeps a connection alive per VU, so in practice
        // one VU sticks to whichever replica it first resolved - a fair demonstration of "no real
        // load balancing", not a trick. AuthApi was never behind nginx (see nginx.conf), so its URL
        // doesn't depend on the toggle at all.
        var env = new List<string>
        {
            $"LINK_API_URL=http://{(_nginxBypassed ? "link-api:8080" : "nginx:8082")}",
            $"REDIRECT_API_URL=http://{(_nginxBypassed ? "redirect-api:8080" : "nginx:8083")}",
            "AUTH_API_URL=http://auth-api:8080",
            $"STEPS_JSON={JsonSerializer.Serialize(resolvedSteps, StepJsonOptions)}",
        };

        if (pool is { Count: > 0 })
        {
            env.Add($"POOL_VAR={poolVar}");
            env.Add($"POOL_MODE={request.DataPool!.Mode}");
            // Only used for flow.js's sequential round-robin spread - a best-effort approximation
            // even during a ramp (Vus there is just the ramp's starting point), which is fine since
            // sequential mode only promises even-ish coverage of the pool, not a strict guarantee.
            env.Add($"POOL_VUS_HINT={Math.Max(1, request.Vus)}");
            env.Add($"POOL_JSON={JsonSerializer.Serialize(pool, StepJsonOptions)}");
        }

        var created = await _client.Containers.CreateContainerAsync(new CreateContainerParameters
        {
            Image = K6Image,
            // grafana/k6's image runs as a non-root user by default, which can't write
            // summary.json into a directory extracted via the Docker API (its permissions don't
            // survive extraction the way a tar mode would suggest - the daemon applies its own
            // umask). Root avoids that fight entirely; this is a throwaway, self-removing
            // container with no docker.sock access, so it's a low-risk place to do it.
            User = "0:0",
            Cmd = cmd,
            Env = env,
            Labels = new Dictionary<string, string> { ["com.docker.compose.project"] = _composeProject },
            HostConfig = new HostConfig { NetworkMode = _composeNetwork },
        }, ct);

        await using (var tarStream = await BuildScriptTarAsync(scriptPath, ct))
        {
            // The destination itself must already exist for the Docker API to accept the
            // extraction - "/" always does, and the tar entry's own "scripts/scenario.js" path
            // makes the extraction create that subdirectory as it unpacks.
            await _client.Containers.ExtractArchiveToContainerAsync(
                created.ID,
                new ContainerPathStatParameters { Path = "/" },
                tarStream,
                ct);
        }

        _logger.LogWarning(
            "Running k6 scenario {Scenario} ({Vus} VUs{Mode}) as {ContainerId}",
            request.Scenario, request.Vus,
            targetIterations is { } t ? $", {t} iterations" : request.Stages is { Count: > 0 } s ? $", {totalSeconds}s, {s.Count} stages" : $", {totalSeconds}s",
            created.ID);

        await _client.Containers.StartContainerAsync(created.ID, new ContainerStartParameters(), ct);

        var output = await StreamLogsWithProgressAsync(created.ID, totalSeconds, targetIterations, onProgress, ct);

        var inspect = await _client.Containers.InspectContainerAsync(created.ID, ct);
        var stepIds = resolvedSteps.Select(s => s.Id).Distinct().ToList();
        var report = await ReadSummaryAsync(created.ID, request.Scenario, stepIds, inspect.State.ExitCode, output, ct);
        await _client.Containers.RemoveContainerAsync(created.ID, new ContainerRemoveParameters(), ct);

        return report;
    }

    // Dispatches on the source id so adding a second DataSourceDefinition later only means adding a
    // case here, not touching RunTrafficAsync. An id that reaches here without a matching case (only
    // possible if DataSourceRegistry grows a source this switch hasn't been taught yet) yields an
    // empty pool rather than throwing - a run should still proceed using the fixture fallback.
    private Task<IReadOnlyList<string>> FetchDataPoolAsync(DataSourceDefinition source, int count, Func<TrafficProgress, Task> onProgress, CancellationToken ct) =>
        source.Id switch
        {
            "link-api.links" => FetchLinkHashesAsync(count, onProgress, ct),
            _ => Task.FromResult<IReadOnlyList<string>>([]),
        };

    // Pages through the real GET /Links (the same nginx-bypass-aware URL k6 itself would use) until
    // `count` hashes are collected or the app runs out of links, pushing a "preparing" progress
    // update after every page so a large pool doesn't look like a hang. Fewer real links existing
    // than requested isn't an error - the pool just ends up smaller, which the caller can see in
    // PreparedCount ending below PreparedTarget in the final push.
    private async Task<IReadOnlyList<string>> FetchLinkHashesAsync(int count, Func<TrafficProgress, Task> onProgress, CancellationToken ct)
    {
        var baseUrl = $"http://{(_nginxBypassed ? "link-api:8080" : "nginx:8082")}";
        var hashes = new List<string>(count);
        var page = 1;

        while (hashes.Count < count)
        {
            HttpResponseMessage response;
            try
            {
                response = await _httpClient.GetAsync($"{baseUrl}/Links?page={page}", ct);
            }
            catch (HttpRequestException ex)
            {
                _logger.LogWarning(ex, "Fetching link pool page {Page} failed - stopping with {Count} collected", page, hashes.Count);
                break;
            }

            if (!response.IsSuccessStatusCode)
            {
                break;
            }

            using var doc = JsonDocument.Parse(await response.Content.ReadAsStreamAsync(ct));
            var items = doc.RootElement.GetProperty("items");
            if (items.GetArrayLength() == 0)
            {
                break;
            }

            foreach (var item in items.EnumerateArray())
            {
                hashes.Add(item.GetProperty("shortenLink").GetString()!);
                if (hashes.Count >= count)
                {
                    break;
                }
            }

            await onProgress(new TrafficProgress(
                0, 0, (int)Math.Min(100, hashes.Count * 100.0 / count), 0, 0, 0,
                Phase: "preparing", PreparedCount: hashes.Count, PreparedTarget: count));

            if (page >= doc.RootElement.GetProperty("totalPages").GetInt32())
            {
                break;
            }

            page++;
        }

        return hashes;
    }

    // Follows the container's combined stdout/stderr as it runs, parsing k6's own once-a-second
    // "running (Ns), X/X VUs, N complete..." status lines into progress pushes, while also
    // building up the full text for the raw-output field of the final report. Returns once the
    // stream hits EOF, which happens when k6 itself exits. targetIterations non-null means an
    // iteration-count run - there's no fixed total time to measure against, so percent comes from
    // iterations done/target instead of elapsed/totalSeconds, and the "past the requested duration"
    // skip below doesn't apply (totalSeconds is 0 in that mode and never meant to bound anything).
    private async Task<string> StreamLogsWithProgressAsync(string containerId, int totalSeconds, int? targetIterations, Func<TrafficProgress, Task> onProgress, CancellationToken ct)
    {
        var logStream = await _client.Containers.GetContainerLogsAsync(
            containerId,
            tty: false,
            new ContainerLogsParameters { ShowStdout = true, ShowStderr = true, Follow = true },
            ct);

        var fullOutput = new StringBuilder();
        var pendingLine = new StringBuilder();
        var buffer = new byte[4096];
        double lastElapsed = 0;
        long lastIterations = 0;

        while (true)
        {
            var result = await logStream.ReadOutputAsync(buffer, 0, buffer.Length, ct);
            if (result.EOF || result.Count == 0)
            {
                break;
            }

            var chunk = Encoding.UTF8.GetString(buffer, 0, result.Count);
            fullOutput.Append(chunk);
            pendingLine.Append(chunk);

            var lines = pendingLine.ToString().Split('\n');
            for (var i = 0; i < lines.Length - 1; i++)
            {
                var match = K6ProgressLine.Match(lines[i]);
                if (!match.Success)
                {
                    continue;
                }

                var hours = match.Groups[1].Success ? double.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture) : 0;
                var minutes = match.Groups[2].Success ? double.Parse(match.Groups[2].Value, CultureInfo.InvariantCulture) : 0;
                var seconds = double.Parse(match.Groups[3].Value, CultureInfo.InvariantCulture);
                var elapsed = hours * 3600 + minutes * 60 + seconds;
                if (targetIterations is null && elapsed > totalSeconds)
                {
                    // k6 prints one extra status line during its graceful-stop tail, past the
                    // requested duration - skip it rather than report a misleading rate spike from
                    // the tiny elapsed delta. Doesn't apply to iteration-count runs, which have no
                    // requested duration to be "past".
                    continue;
                }

                var activeVus = int.Parse(match.Groups[4].Value, CultureInfo.InvariantCulture);
                var iterations = long.Parse(match.Groups[6].Value, CultureInfo.InvariantCulture);
                var elapsedDelta = elapsed - lastElapsed;
                var rate = elapsedDelta > 0 ? (iterations - lastIterations) / elapsedDelta : 0;
                lastElapsed = elapsed;
                lastIterations = iterations;

                var percent = targetIterations is { } target
                    ? (int)Math.Min(100, (double)iterations / target * 100)
                    : (int)Math.Min(100, elapsed / totalSeconds * 100);
                await onProgress(new TrafficProgress((int)elapsed, totalSeconds, percent, activeVus, iterations, rate, targetIterations));
            }

            pendingLine.Clear();
            pendingLine.Append(lines[^1]);
        }

        return fullOutput.ToString();
    }

    public async Task<ResourceSample?> GetResourceSampleAsync(string serviceId, CancellationToken ct)
    {
        var container = await FindAsync(serviceId, ct);
        if (container is null || container.State != "running")
        {
            return null;
        }

        // Stream = false still returns one response with both cpu_stats and precpu_stats
        // populated (two samples internally), which is what the CPU% formula below needs -
        // same as what `docker stats --no-stream` does under the hood.
        ContainerStatsResponse? stats = null;
        await _client.Containers.GetContainerStatsAsync(
            container.ID,
            new ContainerStatsParameters { Stream = false },
            new Progress<ContainerStatsResponse>(s => stats = s),
            ct);

        if (stats is null)
        {
            return null;
        }

        var cpuDelta = (double)(stats.CPUStats.CPUUsage.TotalUsage - stats.PreCPUStats.CPUUsage.TotalUsage);
        var systemDelta = (double)(stats.CPUStats.SystemUsage - stats.PreCPUStats.SystemUsage);
        var onlineCpus = stats.CPUStats.OnlineCPUs > 0 ? stats.CPUStats.OnlineCPUs : (uint)stats.CPUStats.CPUUsage.PercpuUsage.Count;
        var cpuPercent = systemDelta > 0 && cpuDelta > 0 ? cpuDelta / systemDelta * onlineCpus * 100.0 : 0.0;

        return new ResourceSample(serviceId, cpuPercent, (long)stats.MemoryStats.Usage, (long)stats.MemoryStats.Limit, DateTimeOffset.UtcNow);
    }

    public IReadOnlyList<string> ListScalableServices() => ScalableServices;

    public async Task<ScaleResult> ScaleAsync(string serviceId, int replicas, CancellationToken ct)
    {
        if (!ScalableServices.Contains(serviceId))
        {
            return new ScaleResult(serviceId, replicas, false, $"'{serviceId}' is not a scalable service");
        }

        var (exitCode, output) = await RunComposeAsync(
            ["up", "-d", "--scale", $"{serviceId}={replicas}", "--no-recreate", serviceId], null, ct);

        if (exitCode != 0)
        {
            _logger.LogWarning("Scaling {ServiceId} failed (exit {ExitCode}): {Output}", serviceId, exitCode, output);
        }

        return new ScaleResult(serviceId, replicas, exitCode == 0, output);
    }

    // Shared by ScaleAsync and the pgcat/cache infra toggles - all three are "shell out to the real
    // `docker compose` CLI rather than reimplement its logic", just with different args/env.
    // extraEnv is merged into the child process's own environment so docker compose's `${VAR}`
    // interpolation in docker-compose.yml picks it up when re-rendering the target services' config
    // - that's what makes toggling DB_HOST/CACHE_ENABLED actually take effect on recreate.
    private async Task<(int ExitCode, string Output)> RunComposeAsync(IEnumerable<string> args, IDictionary<string, string>? extraEnv, CancellationToken ct)
    {
        var psi = new ProcessStartInfo
        {
            FileName = "docker",
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        foreach (var arg in new[] { "compose", "-p", _composeProject, "-f", _composeFile }.Concat(args))
        {
            psi.ArgumentList.Add(arg);
        }

        if (extraEnv is not null)
        {
            foreach (var (key, value) in extraEnv)
            {
                psi.Environment[key] = value;
            }
        }

        using var process = Process.Start(psi) ?? throw new InvalidOperationException("Failed to start the docker compose process");
        var stdoutTask = process.StandardOutput.ReadToEndAsync(ct);
        var stderrTask = process.StandardError.ReadToEndAsync(ct);
        await process.WaitForExitAsync(ct);
        var output = await stdoutTask + await stderrTask;
        return (process.ExitCode, output);
    }

    public async Task<string?> FlushRedisAsync(CancellationToken ct)
    {
        // FLUSHALL against the master alone is enough - Redis propagates it to redis-replica1/2 via
        // normal command replication, no need to flush each node separately.
        var container = await FindAsync("redis-master", ct);
        if (container is null)
        {
            return null;
        }

        var output = await ExecAsync(container.ID, ["redis-cli", "FLUSHALL"], ct);
        _logger.LogWarning("Flushed Redis cache: {Output}", output.Trim());
        return output.Trim();
    }

    // Runs a command inside a container via Docker's exec API and returns whichever of
    // stdout/stderr actually has content - shared by FlushRedisAsync and the connection-stats
    // queries below, all of which are "shell out to a CLI already inside the target container"
    // rather than adding a new client library dependency (Npgsql, StackExchange.Redis) to
    // control-api just to run one read-only command.
    private async Task<string> ExecAsync(string containerId, IList<string> cmd, CancellationToken ct)
    {
        var exec = await _client.Exec.ExecCreateContainerAsync(containerId, new ContainerExecCreateParameters
        {
            Cmd = cmd,
            AttachStdout = true,
            AttachStderr = true,
        }, ct);

        using var stream = await _client.Exec.StartAndAttachContainerExecAsync(exec.ID, false, ct);
        var (stdout, stderr) = await stream.ReadOutputToEndAsync(ct);
        return string.IsNullOrWhiteSpace(stdout) ? stderr : stdout;
    }

    // `SHOW POOLS` columns (unaligned, pipe-separated): database|user|pool_mode|cl_idle|cl_active|
    // cl_waiting|cl_cancel_req|sv_active|sv_idle|sv_used|sv_tested|sv_login|maxwait|maxwait_us -
    // confirmed against a real pgcat before parsing anything, same discipline as everywhere else
    // this session dealt with an external tool's text output.
    public async Task<PgcatConnectionStats?> GetPgcatConnectionsAsync(CancellationToken ct)
    {
        var container = await FindAsync("pgcat", ct);
        if (container is null)
        {
            return null;
        }

        var output = await ExecAsync(container.ID, ["sh", "-c", "PGPASSWORD=admin_pass psql -h 127.0.0.1 -p 6432 -U admin_user pgcat -tAc \"SHOW POOLS\""], ct);
        var pools = new List<PoolConnectionStats>();
        foreach (var line in output.Split('\n', StringSplitOptions.RemoveEmptyEntries))
        {
            var f = line.Split('|');
            if (f.Length < 10)
            {
                continue;
            }

            pools.Add(new PoolConnectionStats(
                f[0],
                int.Parse(f[3], CultureInfo.InvariantCulture),
                int.Parse(f[4], CultureInfo.InvariantCulture),
                int.Parse(f[5], CultureInfo.InvariantCulture),
                int.Parse(f[7], CultureInfo.InvariantCulture),
                int.Parse(f[8], CultureInfo.InvariantCulture),
                int.Parse(f[9], CultureInfo.InvariantCulture)));
        }

        return new PgcatConnectionStats(pools);
    }

    public async Task<PostgresConnectionStats?> GetPostgresConnectionsAsync(CancellationToken ct)
    {
        var container = await FindAsync("postgres", ct);
        if (container is null)
        {
            return null;
        }

        var output = await ExecAsync(container.ID,
            ["psql", "-U", "postgres", "-tAc", "SELECT datname, count(*) FROM pg_stat_activity WHERE datname IS NOT NULL GROUP BY datname"], ct);

        var byDatabase = new Dictionary<string, int>();
        foreach (var line in output.Split('\n', StringSplitOptions.RemoveEmptyEntries))
        {
            var f = line.Split('|');
            if (f.Length == 2 && int.TryParse(f[1], out var count))
            {
                byDatabase[f[0]] = count;
            }
        }

        return new PostgresConnectionStats(byDatabase, byDatabase.Values.Sum());
    }

    // Redis Sentinel can fail over on its own (see infra/redis/sentinel.conf) - "redis-master" is
    // only a hostname/label in architecture.json, not a guarantee that container is still the one
    // actually serving writes. ROLE is asked of each of the three data nodes directly, not read off
    // Sentinel's own view (see GetSentinelConfigAsync above) - it's the ground truth of what each
    // Redis process itself currently believes it is, and needs no IP-to-container mapping the way
    // reading Sentinel's reported master IP would.
    public async Task<InfraTopology> GetRedisTopologyAsync(CancellationToken ct)
    {
        var roles = new List<NodeRole>();
        foreach (var serviceId in RedisDataNodes)
        {
            var container = await FindAsync(serviceId, ct);
            if (container is null)
            {
                roles.Add(new NodeRole(serviceId, "unreachable"));
                continue;
            }

            try
            {
                var output = await ExecAsync(container.ID, ["redis-cli", "-p", "6379", "ROLE"], ct);
                var role = output.Split('\n', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();
                roles.Add(new NodeRole(serviceId, role switch { "master" => "master", "slave" => "replica", _ => "unreachable" }));
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read Redis ROLE from {ServiceId}", serviceId);
                roles.Add(new NodeRole(serviceId, "unreachable"));
            }
        }

        return new InfraTopology(roles);
    }

    // MongoDB elects its own primary among the replica set members with no external tool involved -
    // the same "the graph's static node labels can lie" problem as Redis Sentinel above. rs.status()
    // has to run against a member that's actually reachable, so this tries mongo1/2/3 in turn and
    // uses whichever first responds; its view covers every member (reachable or not) in one call, so
    // only one successful exec is needed per poll instead of one per node.
    public async Task<InfraTopology> GetMongoTopologyAsync(CancellationToken ct)
    {
        foreach (var serviceId in MongoNodes)
        {
            var container = await FindAsync(serviceId, ct);
            if (container is null)
            {
                continue;
            }

            try
            {
                var output = await ExecAsync(container.ID,
                    ["mongosh", "--quiet", "--eval", "JSON.stringify(rs.status().members.map(m => ({ name: m.name, state: m.stateStr })))"], ct);

                // mongosh can print a version/connection banner before the eval result even with
                // --quiet - slicing from the first '[' skips over that instead of assuming the whole
                // output is clean JSON.
                var start = output.IndexOf('[');
                if (start < 0)
                {
                    continue;
                }

                using var doc = JsonDocument.Parse(output[start..]);
                var roles = new List<NodeRole>();
                foreach (var member in doc.RootElement.EnumerateArray())
                {
                    var name = member.GetProperty("name").GetString() ?? "";
                    var memberServiceId = name.Split(':')[0];
                    var state = member.GetProperty("state").GetString() ?? "";
                    roles.Add(new NodeRole(memberServiceId, state switch
                    {
                        "PRIMARY" => "primary",
                        "SECONDARY" => "secondary",
                        _ => "unreachable",
                    }));
                }

                return new InfraTopology(roles);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read Mongo replica set status from {ServiceId}", serviceId);
            }
        }

        // Every member unreachable (or none responded) - report all three as unreachable rather than
        // an empty list, so the UI still has something to render.
        return new InfraTopology(MongoNodes.Select(id => new NodeRole(id, "unreachable")).ToList());
    }

    // recovery_min_apply_delay is a PGC_SIGHUP GUC on a standby - ALTER SYSTEM SET + pg_reload_conf()
    // applies it live, no restart. pg_settings.setting for a GUC_UNIT_MS parameter is always the raw
    // millisecond integer with no suffix, unlike SHOW's human-formatted output ("5s", "1min", ...) -
    // reading that column instead of parsing SHOW's text is what keeps GetReplicationLagAsync simple.
    public async Task<ReplicationLag?> GetReplicationLagAsync(string serviceId, CancellationToken ct)
    {
        if (!PostgresReplicas.Contains(serviceId))
        {
            return null;
        }

        var container = await FindAsync(serviceId, ct);
        if (container is null)
        {
            return null;
        }

        var output = await ExecAsync(container.ID, ["psql", "-U", "postgres", "-tAc", "SELECT setting FROM pg_settings WHERE name = 'recovery_min_apply_delay'"], ct);
        return new ReplicationLag(int.TryParse(output.Trim(), out var ms) ? ms : 0);
    }

    public async Task<ReplicationLag?> SetReplicationLagAsync(string serviceId, int delayMs, CancellationToken ct)
    {
        if (!PostgresReplicas.Contains(serviceId))
        {
            return null;
        }

        var container = await FindAsync(serviceId, ct);
        if (container is null)
        {
            return null;
        }

        // Two separate exec calls, not one "ALTER SYSTEM SET ...; SELECT pg_reload_conf();" - psql
        // sends a multi-statement -c string as one simple-query message, which Postgres runs inside
        // an implicit transaction block, and ALTER SYSTEM refuses to run inside one (confirmed live:
        // "ERROR: ALTER SYSTEM cannot run inside a transaction block" when combined).
        await ExecAsync(container.ID, ["psql", "-U", "postgres", "-c", $"ALTER SYSTEM SET recovery_min_apply_delay = '{delayMs}ms'"], ct);
        await ExecAsync(container.ID, ["psql", "-U", "postgres", "-c", "SELECT pg_reload_conf()"], ct);
        _logger.LogWarning("Set {ServiceId} replication lag (recovery_min_apply_delay) to {DelayMs}ms", serviceId, delayMs);
        return new ReplicationLag(delayMs);
    }

    // SENTINEL MASTER returns a flat alternating key/value list (confirmed against a real Sentinel
    // before parsing anything) - reads it off redis-sentinel-1 as a representative instance, since a
    // successful SetSentinelConfigAsync keeps all three in sync anyway.
    public async Task<SentinelConfig?> GetSentinelConfigAsync(CancellationToken ct)
    {
        var container = await FindAsync("redis-sentinel-1", ct);
        if (container is null)
        {
            return null;
        }

        var output = await ExecAsync(container.ID, ["redis-cli", "-p", "26379", "SENTINEL", "MASTER", "mymaster"], ct);
        var lines = output.Split('\n', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        var fields = new Dictionary<string, string>();
        for (var i = 0; i + 1 < lines.Length; i += 2)
        {
            fields[lines[i]] = lines[i + 1];
        }

        int Get(string key) => fields.TryGetValue(key, out var v) && int.TryParse(v, out var n) ? n : 0;
        return new SentinelConfig(Get("down-after-milliseconds"), Get("quorum"), Get("failover-timeout"));
    }

    public async Task<SentinelConfig> SetSentinelConfigAsync(SentinelConfig config, CancellationToken ct)
    {
        foreach (var serviceId in SentinelContainers)
        {
            var container = await FindAsync(serviceId, ct);
            if (container is null)
            {
                continue;
            }

            // Three separate SENTINEL SET calls, not one with multiple option/value pairs - kept to
            // exactly the shape already confirmed live against a real Sentinel, one option at a time.
            await ExecAsync(container.ID, ["redis-cli", "-p", "26379", "SENTINEL", "SET", "mymaster", "down-after-milliseconds", config.DownAfterMs.ToString()], ct);
            await ExecAsync(container.ID, ["redis-cli", "-p", "26379", "SENTINEL", "SET", "mymaster", "quorum", config.Quorum.ToString()], ct);
            await ExecAsync(container.ID, ["redis-cli", "-p", "26379", "SENTINEL", "SET", "mymaster", "failover-timeout", config.FailoverTimeoutMs.ToString()], ct);
        }

        _logger.LogWarning(
            "Set Sentinel config on {Containers}: down-after-milliseconds={DownAfterMs}, quorum={Quorum}, failover-timeout={FailoverTimeoutMs}",
            string.Join(", ", SentinelContainers), config.DownAfterMs, config.Quorum, config.FailoverTimeoutMs);

        return config;
    }

    public int GetRabbitMqPrefetch() => _rabbitMqPrefetch;

    public async Task<int> SetRabbitMqPrefetchAsync(int prefetchCount, CancellationToken ct)
    {
        var env = new Dictionary<string, string> { ["RABBITMQ_PREFETCH"] = prefetchCount.ToString() };

        _logger.LogWarning("Switching RabbitMq__PrefetchCount for {Services} to {PrefetchCount}", string.Join(", ", RabbitMqConsumingServices), prefetchCount);
        var (exitCode, output) = await RunComposeAsync(["up", "-d", "--force-recreate", "--no-deps", .. RabbitMqConsumingServices], env, ct);
        if (exitCode != 0)
        {
            _logger.LogWarning("Setting RabbitMQ prefetch failed (exit {ExitCode}): {Output}", exitCode, output);
            throw new InvalidOperationException($"docker compose exited {exitCode}: {output}");
        }

        _rabbitMqPrefetch = prefetchCount;
        return prefetchCount;
    }

    public string GetMongoReadPreference() => _mongoReadPreference;

    public async Task<string> SetMongoReadPreferenceAsync(string preference, CancellationToken ct)
    {
        var env = new Dictionary<string, string> { ["MONGO_READ_PREFERENCE"] = preference };

        _logger.LogWarning("Switching traffic-service's Mongo readPreference to {Preference}", preference);
        var (exitCode, output) = await RunComposeAsync(["up", "-d", "--force-recreate", "--no-deps", "traffic-service"], env, ct);
        if (exitCode != 0)
        {
            _logger.LogWarning("Setting Mongo read preference failed (exit {ExitCode}): {Output}", exitCode, output);
            throw new InvalidOperationException($"docker compose exited {exitCode}: {output}");
        }

        _mongoReadPreference = preference;
        return preference;
    }

    public int GetNpgsqlPoolSize() => _npgsqlPoolSize;

    public async Task<int> SetNpgsqlPoolSizeAsync(int poolSize, CancellationToken ct)
    {
        var env = new Dictionary<string, string> { ["NPGSQL_MAX_POOL_SIZE"] = poolSize.ToString() };

        _logger.LogWarning("Switching Npgsql Maximum Pool Size for {Services} to {PoolSize}", string.Join(", ", DbTouchingServices), poolSize);
        var (exitCode, output) = await RunComposeAsync(["up", "-d", "--force-recreate", "--no-deps", .. DbTouchingServices], env, ct);
        if (exitCode != 0)
        {
            _logger.LogWarning("Setting Npgsql pool size failed (exit {ExitCode}): {Output}", exitCode, output);
            throw new InvalidOperationException($"docker compose exited {exitCode}: {output}");
        }

        _npgsqlPoolSize = poolSize;
        return poolSize;
    }

    public InfraStatus GetInfraStatus() => new(_nginxBypassed, _pgcatEnabled, _cacheEnabled);

    public InfraStatus SetNginxBypass(bool bypassed)
    {
        _logger.LogWarning("Nginx bypass for load-test traffic: {Bypassed}", bypassed);
        _nginxBypassed = bypassed;
        return GetInfraStatus();
    }

    // --no-deps is load-bearing, not cosmetic: --force-recreate on named services also recreates
    // their whole depends_on chain unless told not to (found by hitting it - a pgcat toggle here
    // once cascaded into recreating postgres/redis/rabbitmq/pgcat itself too). That's doubly bad
    // for any service with a *relative* bind mount (pgcat's own pgcat.toml): this docker compose
    // process runs INSIDE control-api, so a path like "./infra/pgcat/pgcat.toml" resolves against
    // control-api's own /workspace view, but the actual container is created by the host's Docker
    // daemon over the socket, which resolves that same string against the real host filesystem -
    // where it doesn't exist, so Docker silently creates it as an empty directory and the mount
    // fails. --no-deps keeps this to exactly the named services, none of which have any volumes.
    public async Task<InfraStatus> SetPgcatEnabledAsync(bool enabled, CancellationToken ct)
    {
        var env = new Dictionary<string, string>
        {
            ["DB_HOST"] = enabled ? "pgcat" : "postgres",
            ["DB_PORT"] = enabled ? "6432" : "5432",
        };

        _logger.LogWarning("Switching DB routing for {Services} to {Host} (pgcat enabled: {Enabled})", string.Join(", ", DbTouchingServices), env["DB_HOST"], enabled);
        var (exitCode, output) = await RunComposeAsync(["up", "-d", "--force-recreate", "--no-deps", .. DbTouchingServices], env, ct);
        if (exitCode != 0)
        {
            _logger.LogWarning("Toggling pgcat failed (exit {ExitCode}): {Output}", exitCode, output);
            throw new InvalidOperationException($"docker compose exited {exitCode}: {output}");
        }

        _pgcatEnabled = enabled;
        return GetInfraStatus();
    }

    public async Task<InfraStatus> SetCacheEnabledAsync(bool enabled, CancellationToken ct)
    {
        var env = new Dictionary<string, string> { ["CACHE_ENABLED"] = enabled ? "true" : "false" };

        _logger.LogWarning("Switching Cache__Enabled for {Services} to {Enabled}", string.Join(", ", CacheUsingServices), enabled);
        var (exitCode, output) = await RunComposeAsync(["up", "-d", "--force-recreate", "--no-deps", .. CacheUsingServices], env, ct);
        if (exitCode != 0)
        {
            _logger.LogWarning("Toggling cache failed (exit {ExitCode}): {Output}", exitCode, output);
            throw new InvalidOperationException($"docker compose exited {exitCode}: {output}");
        }

        _cacheEnabled = enabled;
        return GetInfraStatus();
    }

    public PgcatPoolSettings GetPgcatPoolSettings() => _pgcatPoolSettings;

    // Rewrites pgcat.toml wholesale rather than patching the existing file's text - deterministic
    // and reversible regardless of what the file currently looks like, same reasoning as
    // sentinel.conf being generated fresh at container start rather than edited in place. Written to
    // a *separate* writable bind mount of the same host directory (control-api's own workspace mount
    // is read-only on purpose - see RunComposeAsync's --no-deps comment for the other toggle that
    // learned this the hard way); pgcat itself still mounts the file read-only, but Docker bind
    // mounts are live views of the same host file, so pgcat's own `autoreload = 15000` picks this up
    // within ~15s with no docker compose call at all - no recreate, no --no-deps cascade risk.
    // Collapses the original file's differentiated per-pool sizes (10/20/10) into one shared value -
    // acceptable for an experimental control whose whole point is "what happens if I shrink every
    // pool", not preserving the original tuning.
    public async Task<PgcatPoolSettings> SetPgcatPoolSettingsAsync(PgcatPoolSettings settings, CancellationToken ct)
    {
        var path = Path.Combine(_pgcatConfigDir, "pgcat.toml");
        await File.WriteAllTextAsync(path, RenderPgcatToml(settings), ct);

        _logger.LogWarning(
            "Rewrote pgcat.toml: pool_mode={PoolMode}, read_write_splitting={ReadWriteSplitting}, pool_size={PoolSize} - pgcat autoreload picks this up within ~15s",
            settings.PoolMode, settings.ReadWriteSplitting, settings.PoolSize);

        _pgcatPoolSettings = settings;
        return settings;
    }

    private static readonly IReadOnlyList<string> PgcatDatabases = ["users_db", "links_db", "clicks_db"];

    private static string RenderPgcatToml(PgcatPoolSettings settings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Rewritten live by control-api's pgcat pool-settings control (see DockerService.SetPgcatPoolSettingsAsync).");
        sb.AppendLine("# One primary + 2 streaming replicas (postgres-replica1/2), same trio for all three databases.");
        sb.AppendLine();
        sb.AppendLine("[general]");
        sb.AppendLine("host = \"0.0.0.0\"");
        sb.AppendLine("port = 6432");
        sb.AppendLine("enable_prometheus_exporter = false");
        sb.AppendLine("connect_timeout = 5000");
        sb.AppendLine("idle_timeout = 30000");
        sb.AppendLine("healthcheck_timeout = 1000");
        sb.AppendLine("healthcheck_delay = 30000");
        sb.AppendLine("shutdown_timeout = 5000");
        sb.AppendLine("ban_time = 20");
        sb.AppendLine("log_client_connections = false");
        sb.AppendLine("log_client_disconnections = false");
        sb.AppendLine("autoreload = 15000");
        sb.AppendLine("worker_threads = 4");
        sb.AppendLine("admin_username = \"admin_user\"");
        sb.AppendLine("admin_password = \"admin_pass\"");

        foreach (var database in PgcatDatabases)
        {
            sb.AppendLine();
            sb.AppendLine($"[pools.{database}]");
            sb.AppendLine($"pool_mode = \"{settings.PoolMode}\"");
            sb.AppendLine("default_role = \"primary\"");
            sb.AppendLine("query_parser_enabled = true");
            sb.AppendLine($"query_parser_read_write_splitting = {(settings.ReadWriteSplitting ? "true" : "false")}");
            sb.AppendLine("primary_reads_enabled = true");
            sb.AppendLine();
            sb.AppendLine($"[pools.{database}.users.0]");
            sb.AppendLine("username = \"postgres\"");
            sb.AppendLine("password = \"postgres\"");
            sb.AppendLine($"pool_size = {settings.PoolSize}");
            sb.AppendLine("statement_timeout = 0");
            sb.AppendLine();
            sb.AppendLine($"[pools.{database}.shards.0]");
            sb.AppendLine("servers = [[\"postgres\", 5432, \"primary\"], [\"postgres-replica1\", 5432, \"replica\"], [\"postgres-replica2\", 5432, \"replica\"]]");
            sb.AppendLine($"database = \"{database}\"");
        }

        return sb.ToString();
    }

    public IReadOnlyList<EndpointDefinition> ListKnownEndpoints() => EndpointRegistry;

    public IReadOnlyList<DataSourceDefinition> ListDataSources() => DataSourceRegistry;

    private async Task<TrafficReport> ReadSummaryAsync(string containerId, string scenario, IReadOnlyList<string> stepIds, long exitCode, string rawOutput, CancellationToken ct)
    {
        try
        {
            var response = await _client.Containers.GetArchiveFromContainerAsync(
                containerId, new GetArchiveFromContainerParameters { Path = "/scripts/summary.json" }, false, ct);

            // Buffer fully before handing to TarReader - it does non-sequential-looking reads via
            // SubReadStream over each entry's data, which doesn't play well with the raw chunked
            // HTTP stream the Docker API hands back (hit EndOfStreamException reading directly).
            using var buffered = new MemoryStream();
            await response.Stream.CopyToAsync(buffered, ct);
            buffered.Position = 0;

            using var reader = new TarReader(buffered);
            TarEntry? entry;
            while ((entry = await reader.GetNextEntryAsync(cancellationToken: ct)) is not null)
            {
                if (entry.DataStream is null)
                {
                    continue;
                }

                using var streamReader = new StreamReader(entry.DataStream);
                var json = await streamReader.ReadToEndAsync(ct);
                return ParseSummary(json, scenario, stepIds, exitCode, rawOutput);
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not read k6 summary.json for {Scenario} - falling back to raw output only", scenario);
        }

        return new TrafficReport(scenario, exitCode, 0, 0, 0, 0, 0, 0, 0, null, [], [], rawOutput);
    }

    // Only status codes k6 was explicitly told to track (via a trivial always-passing threshold on
    // "http_reqs{status:X}" - see each k6-scripts/*.js) end up as separate entries in the summary
    // JSON at all; anything not listed here still counts toward the overall http_reqs total, it
    // just won't be broken out by code. "0" is k6's own status for a request that got no HTTP
    // response whatsoever (connection refused/reset, or timed out) - genuinely different from a
    // server responding with an error code, so it gets its own human-readable label instead of "0".
    private static readonly IReadOnlyList<(string Code, string Label)> TrackedStatusCodes =
    [
        ("200", "200 OK"),
        ("302", "302 Found"),
        ("401", "401 Unauthorized"),
        ("404", "404 Not Found"),
        ("409", "409 Conflict"),
        ("500", "500 Internal Server Error"),
        ("502", "502 Bad Gateway"),
        ("503", "503 Service Unavailable"),
        ("504", "504 Gateway Timeout"),
        ("0", "No response (connection error / timeout)"),
    ];

    private static TrafficReport ParseSummary(string json, string scenario, IReadOnlyList<string> stepIds, long exitCode, string rawOutput)
    {
        using var doc = JsonDocument.Parse(json);
        var metrics = doc.RootElement.GetProperty("metrics");

        long GetCount(string metric) =>
            metrics.TryGetProperty(metric, out var m) && m.TryGetProperty("count", out var c) ? c.GetInt64() : 0;
        double GetRate(string metric) =>
            metrics.TryGetProperty(metric, out var m) && m.TryGetProperty("rate", out var r) ? r.GetDouble() : 0;
        double GetValue(string metric) =>
            metrics.TryGetProperty(metric, out var m) && m.TryGetProperty("value", out var v) ? v.GetDouble() : 0;
        // http_req_failed is a k6 Rate metric: "passes" is the count of samples where the request
        // was considered failed (value 1), not a count of successes - the passes/fails naming is
        // generic to Rate metrics (also used by "checks", where 1 *does* mean success) and doesn't
        // flip meaning per-metric, so this needs to be read deliberately rather than by the names.
        long GetFailedCount(string metric) =>
            metrics.TryGetProperty(metric, out var m) && m.TryGetProperty("passes", out var p) ? p.GetInt64() : 0;

        LatencyStats? duration = null;
        if (metrics.TryGetProperty("http_req_duration", out var d))
        {
            double Field(string name) => d.TryGetProperty(name, out var v) ? v.GetDouble() : 0;
            duration = new LatencyStats(Field("avg"), Field("min"), Field("med"), Field("max"), Field("p(90)"), Field("p(95)"));
        }

        var checks = new List<CheckResult>();
        if (doc.RootElement.TryGetProperty("root_group", out var rootGroup) && rootGroup.TryGetProperty("checks", out var checksObj))
        {
            foreach (var check in checksObj.EnumerateObject())
            {
                var passes = check.Value.TryGetProperty("passes", out var p) ? p.GetInt32() : 0;
                var fails = check.Value.TryGetProperty("fails", out var f) ? f.GetInt32() : 0;
                checks.Add(new CheckResult(check.Name, passes, fails));
            }
        }

        // Each request is tagged with its originating step id (see flow.js), and flow.js declares a
        // threshold for every (stepId, trackedStatusCode) pair up front - only tag combinations with
        // a declared threshold get retained/exported by k6 at all, and only ones that actually
        // occurred (Count > 0) are worth showing.
        var statusByEndpoint = stepIds
            .Select(id => new EndpointStatusBreakdown(
                id,
                TrackedStatusCodes
                    .Select(sc => new StatusCount(sc.Label, GetCount($"http_reqs{{step:{id},status:{sc.Code}}}")))
                    .Where(sc => sc.Count > 0)
                    .OrderByDescending(sc => sc.Count)
                    .ToList()))
            .Where(e => e.StatusCounts.Count > 0)
            .ToList();

        return new TrafficReport(
            scenario,
            exitCode,
            GetCount("http_reqs"),
            GetRate("http_reqs"),
            GetFailedCount("http_req_failed"),
            GetValue("http_req_failed"),
            GetCount("iterations"),
            GetRate("iterations"),
            (int)GetValue("vus_max"),
            duration,
            checks,
            statusByEndpoint,
            rawOutput);
    }

    private static async Task<MemoryStream> BuildScriptTarAsync(string scriptPath, CancellationToken ct)
    {
        var tarStream = new MemoryStream();
        await using (var writer = new TarWriter(tarStream, TarEntryFormat.Pax, leaveOpen: true))
        {
            // Without an explicit directory entry, the extraction still creates "scripts/" (to
            // hold scenario.js) but with a restrictive default mode - grafana/k6 runs as a
            // non-root user and needs write access on this directory itself to later create
            // summary.json there, not just read access to the script file inside it.
            var dirEntry = new PaxTarEntry(TarEntryType.Directory, "scripts/") { Mode = (UnixFileMode)0777 };
            await writer.WriteEntryAsync(dirEntry, ct);

            var fileEntry = new PaxTarEntry(TarEntryType.RegularFile, "scripts/scenario.js")
            {
                DataStream = File.OpenRead(scriptPath),
                Mode = (UnixFileMode)0644,
            };
            await writer.WriteEntryAsync(fileEntry, ct);
        }

        tarStream.Position = 0;
        return tarStream;
    }

    private async Task EnsureImageAsync(string image, CancellationToken ct)
    {
        var existing = await _client.Images.ListImagesAsync(new ImagesListParameters
        {
            Filters = new Dictionary<string, IDictionary<string, bool>>
            {
                ["reference"] = new Dictionary<string, bool> { [image] = true },
            },
        }, ct);

        if (existing.Count > 0)
        {
            return;
        }

        var parts = image.Split(':', 2);
        _logger.LogInformation("Pulling {Image} (first use)", image);
        await _client.Images.CreateImageAsync(
            new ImagesCreateParameters { FromImage = parts[0], Tag = parts.Length > 1 ? parts[1] : "latest" },
            null,
            new Progress<JSONMessage>(),
            ct);
    }

    private async Task<ContainerListResponse?> FindAsync(string serviceId, CancellationToken ct)
    {
        var containers = await _client.Containers.ListContainersAsync(new ContainersListParameters
        {
            All = true,
            Filters = new Dictionary<string, IDictionary<string, bool>>
            {
                ["label"] = new Dictionary<string, bool>
                {
                    [$"com.docker.compose.project={_composeProject}"] = true,
                    [$"com.docker.compose.service={serviceId}"] = true,
                },
            },
        }, ct);

        return containers.FirstOrDefault();
    }

    private static ManagedContainer? ToStatus(ContainerListResponse container)
    {
        if (!container.Labels.TryGetValue("com.docker.compose.service", out var serviceId))
        {
            return null;
        }

        var containerNumber = container.Labels.TryGetValue("com.docker.compose.container-number", out var n) && int.TryParse(n, out var parsed)
            ? parsed
            : 1;

        return new ManagedContainer(serviceId, container.ID, container.State, container.Status, containerNumber);
    }
}
